moveit_simple_controller_manager:
  controller_names:
    - dg5f_right_controller

  dg5f_right_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - rj_dg_1_1
      - rj_dg_1_2
      - rj_dg_1_3
      - rj_dg_1_4
      - rj_dg_2_1
      - rj_dg_2_2
      - rj_dg_2_3
      - rj_dg_2_4
      - rj_dg_3_1
      - rj_dg_3_2
      - rj_dg_3_3
      - rj_dg_3_4
      - rj_dg_4_1
      - rj_dg_4_2
      - rj_dg_4_3
      - rj_dg_4_4
      - rj_dg_5_1
      - rj_dg_5_2
      - rj_dg_5_3
      - rj_dg_5_4
